cursor #e6e0e9
cursor_text_color #cac4cf

foreground            #e6e0e9
background            #141218
selection_foreground  #332d41
selection_background  #ccc2db
url_color             #d0bcfe
color0   #141218
color1   #d55958
color2   #8ed88c
color3   #e0d99d
color4   #916ce2
color5   #a296be
color6   #d0bcfe
color7   #abb2bf
color8   #5c6370
color9   #e57e7e
color10   #a2e5a0
color11   #efe9b3
color12   #dfc9ff
color13   #7c6bce
color14   #8a6bb5
color15   #ffffff
