#! /bin/sh

# Polybar
$HOME/.config/polybar/launch.sh

# Nitrogen
# $HOME/.config/bspwm/nitrogen/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d          

bspc config border_width        1
bspc config window_gap          2
bspc config split_ratio         0.52

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config focus_follows_pointer true

bspc config focused_border_color "#7c4dff"
# bspc config normal_border_coler  ""
# bspc config active_border_color ""
# bspc config presel_feedback_color ""

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunar desktop='^5' follow=on focus=on
bspc rule -a Code desktop='^3' follow=on focus=on
bspc rule -a pdf desktop='^9' follow=on focus=on
bspc rule -a Alacritty desktop='^6' follow=on focus=on
bspc rule -a Nitrogen desktop='^10' follow=on focus=on

# ================= Mouse Events ===============
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# ====== Enable Super Keys For menu ===========
killall ksuperkey
ksuperkey -e 'Super_R=Alt_L|F1' &
ksuperkey -d &
